// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqbzcxizlkazhalivqox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxYnpjeGl6bGthemhhbGl2cW94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2NzczMzQsImV4cCI6MjA3ODI1MzMzNH0.xOmFEE0j8PBXCoL3nVgIf62YTMlSKWbz950gjsaGm8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});